services:
  - type: web
    name: tra-api-backend
    env: python
    runtime: python
    buildCommand: ./build.sh
    startCommand: python -m uvicorn server:app --host 0.0.0.0 --port $PORT
    pythonVersion: "3.11.9"

  - type: web
    name: tra-api-tester
    env: static
    buildCommand: cd frontend-testing-tool && npm install && npm run build
    staticPublishPath: ./frontend-testing-tool/build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0 